
Vagrant.configure("2") do |config|
  
    config.vm.define "windows" do |windows|
    config.vm.box = "StefanScherer/windows_10"
    config.vm.communicator = "winrm"
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
    config.vm.guest = :windows 
    config.vm.hostname = "Arc-Win10-Demo"
    config.vm.synced_folder ".", "/vagrant" , type:"rsync"
    config.vm.box_download_insecure = true
    

   end

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false 
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"   
  end

  # View the documentation for the provider you are using for more
  # information on available options.
  
end